module.exports = {
  "REACT_APP_BUILD_NUMBER": process.env.TRAVIS_BUILD_NUMBER,
  "REACT_APP_MAP_KEY": process.env.MAP_STAGING_KEY,
  "REACT_APP_FIREBASE_API_KEY": process.env.FIREBASE_STAGING_API_KEY,
  "REACT_APP_FIREBASE_APP_ID": process.env.FIREBASE_STAGING_APP_ID,
  "REACT_APP_FIREBASE_AUTH_DOMAIN": process.env.FIREBASE_STAGING_DOMAIN,
  "REACT_APP_FIREBASE_DATABASE_URL": process.env.FIREBASE_STAGING_DATABASE_URL,
  "REACT_APP_FIREBASE_PROJECT_ID": process.env.FIREBASE_STAGING_PROJECT_ID,
  "REACT_APP_FIREBASE_BUCKET": process.env.FIREBASE_STAGING_BUCKET,
  "REACT_APP_FIREBASE_MESSAGING_ID": process.env.FIREBASE_STAGING_MESSAGING_ID
}
