module.exports = {
  "REACT_APP_MAP_KEY": process.env.MAP_PROD_KEY,
  "REACT_APP_FIREBASE_API_KEY": process.env.FIREBASE_PROD_API_KEY,
  "REACT_APP_FIREBASE_APP_ID": process.env.FIREBASE_PROD_APP_ID,
  "REACT_APP_FIREBASE_AUTH_DOMAIN": process.env.FIREBASE_PROD_DOMAIN,
  "REACT_APP_FIREBASE_DATABASE_URL": process.env.FIREBASE_PROD_DATABASE_URL,
  "REACT_APP_FIREBASE_PROJECT_ID": process.env.FIREBASE_PROD_PROJECT_ID,
  "REACT_APP_FIREBASE_BUCKET": process.env.FIREBASE_PROD_BUCKET,
  "REACT_APP_FIREBASE_MESSAGING_ID": process.env.FIREBASE_PROD_MESSAGING_ID
}